### ISSUE TITLE
about SHAs

### ISSUE THREAD

**Issue by nori-li** [n1tecki/Geography-of-Open-Source-Software#2]
Hello. I am new here. I want to ask you, what is SHAs?

**Comment by johanneswachs** [comment]
Hi Nori-li - thanks for checking in! SHAs are unique identifiers of commits. This video goes into a bit more detail: https://teamtreehouse.com/library/introduction-to-git/commit-shas-and-undoing-commits#:~:text=%22SHA%22%20stands%20for%20Simple%20Hashing,checksum%20uniquely%20identifies%20a%20commit.

Hope that helps!

**Comment by nori-li** [comment]
Thank you，haha.
