### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by nori-li** [n1tecki/Geography-of-Open-Source-Software#3]
I tried to run this code, but failed.
1. What version of Python do you use?
2.github_ tokens.csv  Is there no data in this file?
3. Are the caching in import caching packaged by you?

**Comment by johanneswachs** [comment]
Hi!
- We are using Python 3 (I guess anything >3.4 should work!)
- you will need to register for some github API tokens yourself and add them to your copy of the CSV. 
I'm afraid I don't follow the last question - could you point to a specific file?

**Comment by nori-li** [comment]
![image](https://user-images.githubusercontent.com/43471922/199016193-569e5017-d59b-439d-b198-8720136d253c.png)
Did you encapsulate this file yourself?The one framed in red.

**Comment by johanneswachs** [comment]
Yes - see: https://github.com/n1tecki/Geography-of-Open-Source-Software/blob/main/code/Resources/caching.py
